# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
 - package-ecosystem: "devcontainers"
   directory: "/"
   schedule:
     interval: weekly
 - package-ecosystem: "nuget"
   directory: "/"
   schedule:
     interval: weekly
   groups:
     security:
       dependency-type: "production"
       applies-to: security-updates
       update-types:
        - "patch"
        - "minor"
     production:
       dependency-type: "production"
       applies-to: version-updates
       update-types:
        - "patch"
        - "minor"
    development:
      dependency-type: "development"
      update-types:
        - "patch"
        - "minor"
      
