name: Workflow Manual

on:
  workflow_dispatch:
    inputs:
      runs-on:
        description: The OS to run on
        default: ubuntu-latest
        required: false
      dotnet-version:
        description: The dotnet version specifier
        default: 8.x.x
        required: false
      dotnet-verbosity:
        type: string
        description: Verbosity of dotnet commands
        required: false
        default: normal
      configuration:
        description: The configuration to build
        default: Release
        required: false
      package:
        description: Pack and upload as an artifact
        type: boolean
        required: false
        default: false
      workflow-print-context:
        description: Print the github context as a step
        type: boolean
        required: false
        default: false
      upload-coverage:
        description: Upload code coverage
        type: boolean
        required: false
        default: false
      upload-coverage-verbose:
        description: Upload code coverage with verbose output
        type: boolean
        required: false
        default: false

jobs:
  print-context:
    runs-on: ubuntu-latest
    if: github.event.inputs.workflow-print-context == 'true'
    steps:
    - env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  call-ci:
    uses: ./.github/workflows/ci-call.yml
    with:
      runs-on: ${{ github.event.inputs.runs-on }}
      dotnet-version: ${{ github.event.inputs.dotnet-version }}
      dotnet-verbosity: ${{ github.event.inputs.dotnet-verbosity }}
      configuration:  ${{ github.event.inputs.configuration }}
      package: ${{ github.event.inputs.package == 'true' }}
      upload-coverage: ${{ github.event.inputs.upload-coverage == 'true' }}
      upload-coverage-verbose: ${{ github.event.inputs.upload-coverage-verbose == 'true' }}
