name: NuGet Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: 🎢 Download artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: dotnet.yml
          commit: ${{ env.GITHUB_SHA }}
          name: nupkg
          path: nupkg
          check_artifacts: true
      - name: 🌐 Push to GitHub Feed
        run: dotnet nuget push ./nupkg/*.nupkg --source $NUGET_FEED --skip-duplicate --api-key $AUTH_TOKEN
        env:
          GITHUB_USER: trippwill
          AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_FEED: https://nuget.pkg.github.com/trippwill/index.json
      - name: 🌐 Push to NuGet Feed
        run: dotnet nuget push ./nupkg/*.nupkg --source https://api.nuget.org/v3/index.json --skip-duplicate --api-key $AUTH_TOKEN
        env:
          AUTH_TOKEN: ${{ secrets.NUGET_PUSH_KEY }}

